image:
  repository: ard3ny/velero-backup-notification
  tag: v1.0.5

slack:
  enabled: false
  failures_only: true
  webhook: "https://...."
  channel: "stuff"
  username: Velero

discord:
  enabled: false
  failures_only: false
  webhook: "https://discord.com/api/webhooks/1267393565131280434/1c5vBQoZEWD3nTfYlpiCrOhGyvZ0PIhXqK0_nPkwLvcyPHeH5S8pgM4gNJQuvJEREsiB"
  mentions:
    enabled: false
    failures_only: true
    role_id: "1234567890"

email:
  enabled: false
  failures_only: true
  smtp:
    host: some-smtp-host.com
    port: 587
    username: blah
    password: blah
  from_address: from@email.com
  to_address: to@email.com


webhook:
  enabled: false
  failures_only: false
  url: "https://...."

velero_namespace: filip-velero
partially_failed_count_as_completed: false
notification_prefix: "[Velero] "