image:
  repository: ard3ny/velero-backup-notification
  tag: v1.0.4

slack:
  enabled: false
  failures_only: true
  webhook: "https://...."
  channel: "stuff"
  username: Velero

discord:
  enabled: false
  failures_only: true
  partially_failures_counts_as_complete: false
  webhook: "https://...."
  mentions:
    enabled: false
    failures_only: true
    role_id: "1234567890"

email:
  enabled: false
  failures_only: true
  smtp:
    host: some-smtp-host.com
    port: 587
    username: blah
    password: blah
  from_address: from@email.com
  to_address: to@email.com


webhook:
  enabled: false
  failures_only: false
  url: "https://...."

velero_namespace: velero

notification_prefix: "[Velero] "
